const capabilityNames = [
  "setup",
  "dense_search",
  "point_scroll",
  "count",
  "facets",
  "grouped_search",
  "recall_check",
  "text_hybrid",
  "graph_first",
  "vector_first",
  "rank_fusion",
  "joint",
] as const

export const availableCapabilities = (overrides: Readonly<Record<string, unknown>> = {}) => ({
  request_id: "req_capabilities",
  contract_version: "context.v1",
  product_status: "preview",
  pgcontext_compatibility: {
    target_version: "0.2.0",
    stable_items: 1,
    aligned: 1,
    managed_equivalent: 0,
    partial: 0,
    sql_only: 0,
    deferred: 0,
    missing_sdk: 0,
  },
  runtime: {
    postgres_major: 17,
    pgcontext_version: "0.2.0",
    pgcontext_source_commit: "synthetic",
    pgvector_installed: true,
    pgcontext_installed: true,
    pgvector_version: "0.8.0",
    pgvector_schema: "public",
    pgcontext_pgvector_version: "0.8.0",
    same_column_bridge: false,
  },
  ...Object.fromEntries(
    capabilityNames.flatMap((name) => [
      [name, true],
      [`${name}_blocker`, null],
      [`${name}_blocker_message`, null],
    ]),
  ),
  ranked_search_cursor: false,
  max_dimensions: 4_096,
  max_search_limit: 1_000,
  max_context_limit: 1_000,
  max_graph_limit: 1_000,
  max_joint_seed_limit: 32,
  max_joint_traversal_limit: 1_000,
  max_graph_depth: 20,
  max_relationship_types: 32,
  max_result_columns: 32,
  max_filter_bytes: 65_536,
  max_filter_depth: 16,
  max_filter_nodes: 256,
  max_filter_values: 2_000,
  max_values_per_match: 500,
  max_reconcile_point_keys: 10_000,
  max_point_keys_per_operation: 10_000,
  ...overrides,
})
