export type ContextHttpMethod = "DELETE" | "GET" | "PATCH" | "POST" | "PUT"
export type ContextRetryPolicy = "idempotentMutation" | "never" | "readOnlyGet" | "readOnlyPost"
export type ContextPagination = "cursor" | "none"
export type ContextRequestBody = "none" | "required"

export interface ContextOperationBinding {
  readonly kind: "operation"
  readonly publicName: string
  readonly operationId: string
  readonly method: ContextHttpMethod
  readonly path: string
  readonly retryPolicy: ContextRetryPolicy
  readonly pagination: ContextPagination
  readonly requestBody: ContextRequestBody
}

export interface ContextLocalBinding {
  readonly kind: "local"
  readonly publicName: string
}

export interface ContextPollingCompositeBinding {
  readonly kind: "composite"
  readonly publicName: "waitForOperation"
  readonly operationId: "runtime_context_get_operation"
  readonly method: "GET"
  readonly path: "/v1/context/operations/{operation_id}"
  readonly retryPolicy: "polling"
  readonly pagination: "none"
  readonly requestBody: "none"
}

export type ContextBinding = ContextOperationBinding | ContextLocalBinding | ContextPollingCompositeBinding

type OperationTuple = readonly [
  publicName: string,
  operationId: string,
  method: ContextHttpMethod,
  path: string,
  retryPolicy: ContextRetryPolicy,
  pagination: ContextPagination,
  requestBody: ContextRequestBody,
]

// Hand-reviewed against the pinned method manifest; runtime code never loads contract data.
const operations = [
  [
    "acknowledgeOnboarding",
    "runtime_context_acknowledge_onboarding",
    "POST",
    "/v1/context/onboarding/acknowledge",
    "idempotentMutation",
    "none",
    "required",
  ],
  [
    "addFilterColumn",
    "runtime_context_add_filter_column",
    "POST",
    "/v1/context/collections/{collection_id}/filters/columns",
    "idempotentMutation",
    "none",
    "required",
  ],
  [
    "addJsonbFilterPath",
    "runtime_context_add_filter_jsonb_path",
    "POST",
    "/v1/context/collections/{collection_id}/filters/jsonb-paths",
    "idempotentMutation",
    "none",
    "required",
  ],
  [
    "addVector",
    "runtime_context_add_vector",
    "POST",
    "/v1/context/collections/{collection_id}/vectors",
    "idempotentMutation",
    "none",
    "required",
  ],
  [
    "backfillPoints",
    "runtime_context_backfill_points",
    "POST",
    "/v1/context/points/backfill",
    "never",
    "none",
    "required",
  ],
  [
    "bulkDeletePoints",
    "runtime_context_bulk_delete_points",
    "POST",
    "/v1/context/points/bulk-delete",
    "never",
    "none",
    "required",
  ],
  [
    "bulkUpsertPoints",
    "runtime_context_bulk_upsert_points",
    "POST",
    "/v1/context/points/bulk-upsert",
    "never",
    "none",
    "required",
  ],
  [
    "cancelOperation",
    "runtime_context_cancel_operation",
    "POST",
    "/v1/context/operations/{operation_id}/cancel",
    "idempotentMutation",
    "none",
    "required",
  ],
  [
    "candidateSearch",
    "runtime_context_candidate_search",
    "POST",
    "/v1/context/search/candidates",
    "never",
    "none",
    "required",
  ],
  [
    "clearPayload",
    "runtime_context_clear_payload",
    "POST",
    "/v1/context/points/payload/clear",
    "never",
    "none",
    "required",
  ],
  [
    "collectionAliases",
    "runtime_context_list_collection_aliases",
    "GET",
    "/v1/context/aliases",
    "readOnlyGet",
    "none",
    "none",
  ],
  [
    "collectionInfo",
    "runtime_context_collection_info",
    "GET",
    "/v1/context/collections/by-name/{collection_name}/info",
    "readOnlyGet",
    "none",
    "none",
  ],
  [
    "collectionLimits",
    "runtime_context_collection_limits",
    "GET",
    "/v1/context/collections/by-name/{collection_name}/limits",
    "readOnlyGet",
    "none",
    "none",
  ],
  [
    "collectionVectors",
    "runtime_context_collection_vectors",
    "GET",
    "/v1/context/collections/by-name/{collection_name}/vectors",
    "readOnlyGet",
    "none",
    "none",
  ],
  [
    "configureCollectionLimits",
    "runtime_context_configure_collection_limits",
    "PATCH",
    "/v1/context/collections/by-name/{collection_name}/limits",
    "never",
    "none",
    "required",
  ],
  [
    "configureVector",
    "runtime_context_configure_vector",
    "PATCH",
    "/v1/context/collections/by-name/{collection_name}/vectors/{vector_name}",
    "never",
    "none",
    "required",
  ],
  ["count", "runtime_context_count", "POST", "/v1/context/count", "readOnlyPost", "none", "required"],
  [
    "createCollection",
    "runtime_context_create_collection",
    "POST",
    "/v1/context/collections",
    "idempotentMutation",
    "none",
    "required",
  ],
  [
    "createCollectionAlias",
    "runtime_context_create_collection_alias",
    "POST",
    "/v1/context/aliases",
    "never",
    "none",
    "required",
  ],
  [
    "createEmbeddingMigration",
    "runtime_context_create_embedding_migration",
    "POST",
    "/v1/context/collections/by-name/{collection_name}/embedding-migrations",
    "never",
    "none",
    "required",
  ],
  [
    "deleteCollection",
    "runtime_context_delete_collection",
    "DELETE",
    "/v1/context/collections/{collection_id}",
    "idempotentMutation",
    "none",
    "required",
  ],
  [
    "deletePayload",
    "runtime_context_delete_payload",
    "POST",
    "/v1/context/points/payload/delete",
    "never",
    "none",
    "required",
  ],
  [
    "deletePoints",
    "runtime_context_delete_points",
    "POST",
    "/v1/context/collections/{collection_id}/points/delete",
    "idempotentMutation",
    "none",
    "required",
  ],
  ["discover", "runtime_context_discover_points", "POST", "/v1/context/search/discover", "never", "none", "required"],
  ["discoverSources", "runtime_context_discover", "POST", "/v1/context/discover", "readOnlyPost", "none", "required"],
  [
    "dismissOnboarding",
    "runtime_context_dismiss_onboarding",
    "POST",
    "/v1/context/onboarding/dismiss",
    "idempotentMutation",
    "none",
    "required",
  ],
  [
    "dropCollection",
    "runtime_context_delete_collection",
    "DELETE",
    "/v1/context/collections/{collection_id}",
    "idempotentMutation",
    "none",
    "required",
  ],
  [
    "dropCollectionAlias",
    "runtime_context_drop_collection_alias",
    "DELETE",
    "/v1/context/aliases/{alias_name}",
    "never",
    "none",
    "none",
  ],
  [
    "embeddingMigrations",
    "runtime_context_embedding_migrations",
    "GET",
    "/v1/context/collections/by-name/{collection_name}/embedding-migrations",
    "readOnlyGet",
    "none",
    "none",
  ],
  [
    "estimateIndexMemory",
    "runtime_context_estimate_index_memory",
    "GET",
    "/v1/context/collections/by-name/{collection_name}/indexes/{index_name}/memory-estimate",
    "readOnlyGet",
    "none",
    "none",
  ],
  [
    "evaluateOnboarding",
    "runtime_context_evaluate_onboarding",
    "POST",
    "/v1/context/onboarding/evaluate",
    "readOnlyPost",
    "none",
    "required",
  ],
  ["executeQuery", "runtime_context_execute_query", "POST", "/v1/context/query/execute", "never", "none", "required"],
  ["explain", "runtime_context_explain_query", "POST", "/v1/context/query/explain", "never", "none", "required"],
  ["explore", "runtime_context_explore", "POST", "/v1/context/explore", "never", "none", "required"],
  ["facet", "runtime_context_facets", "POST", "/v1/context/facets", "readOnlyPost", "none", "required"],
  ["facets", "runtime_context_facets", "POST", "/v1/context/facets", "readOnlyPost", "none", "required"],
  ["getCapabilities", "runtime_context_capabilities", "GET", "/v1/context/capabilities", "readOnlyGet", "none", "none"],
  [
    "getCollection",
    "runtime_context_get_collection",
    "GET",
    "/v1/context/collections/{collection_id}",
    "readOnlyGet",
    "none",
    "none",
  ],
  [
    "getCollectionDiagnostics",
    "runtime_context_get_diagnostics",
    "GET",
    "/v1/context/collections/{collection_id}/diagnostics",
    "readOnlyGet",
    "none",
    "none",
  ],
  [
    "getCollectionStatus",
    "runtime_context_get_status",
    "GET",
    "/v1/context/collections/{collection_id}/status",
    "readOnlyGet",
    "none",
    "none",
  ],
  ["getOnboarding", "runtime_context_get_onboarding", "GET", "/v1/context/onboarding", "readOnlyGet", "none", "none"],
  [
    "getOperation",
    "runtime_context_get_operation",
    "GET",
    "/v1/context/operations/{operation_id}",
    "readOnlyGet",
    "none",
    "none",
  ],
  [
    "getPointStatus",
    "runtime_context_get_point_status",
    "GET",
    "/v1/context/collections/{collection_id}/points/status",
    "readOnlyGet",
    "none",
    "none",
  ],
  ["graphFirst", "runtime_context_graph_first", "POST", "/v1/context/hybrid/graph-first", "never", "none", "required"],
  [
    "groupedSearch",
    "runtime_context_grouped_search",
    "POST",
    "/v1/context/grouped-search",
    "never",
    "none",
    "required",
  ],
  [
    "indexAdvisor",
    "runtime_context_index_advisor",
    "GET",
    "/v1/context/collections/by-name/{collection_name}/index-advisor",
    "readOnlyGet",
    "none",
    "none",
  ],
  [
    "indexDiagnostics",
    "runtime_context_index_diagnostics",
    "GET",
    "/v1/context/collections/by-name/{collection_name}/indexes/{index_name}/diagnostics",
    "readOnlyGet",
    "none",
    "none",
  ],
  [
    "indexStatus",
    "runtime_context_index_status",
    "GET",
    "/v1/context/collections/by-name/{collection_name}/indexes/{index_name}/status",
    "readOnlyGet",
    "none",
    "none",
  ],
  ["joint", "runtime_context_joint", "POST", "/v1/context/hybrid/joint", "never", "none", "required"],
  [
    "listCollections",
    "runtime_context_list_collections",
    "GET",
    "/v1/context/collections",
    "readOnlyGet",
    "cursor",
    "none",
  ],
  [
    "listFilters",
    "runtime_context_list_filters",
    "GET",
    "/v1/context/collections/{collection_id}/filters",
    "readOnlyGet",
    "none",
    "none",
  ],
  [
    "listOperations",
    "runtime_context_list_operations",
    "GET",
    "/v1/context/operations",
    "readOnlyGet",
    "cursor",
    "none",
  ],
  [
    "modelVersions",
    "runtime_context_model_versions",
    "GET",
    "/v1/context/collections/by-name/{collection_name}/model-versions",
    "readOnlyGet",
    "none",
    "none",
  ],
  [
    "optimizationStatus",
    "runtime_context_optimization_status",
    "GET",
    "/v1/context/collections/by-name/{collection_name}/optimization-status",
    "readOnlyGet",
    "none",
    "none",
  ],
  ["preflight", "runtime_context_preflight", "POST", "/v1/context/preflight", "readOnlyPost", "none", "required"],
  ["query", "runtime_context_text_hybrid", "POST", "/v1/context/hybrid/text", "never", "none", "required"],
  [
    "queryCohortStats",
    "runtime_context_query_cohort_stats",
    "GET",
    "/v1/context/collections/by-name/{collection_name}/query-cohort-stats",
    "readOnlyGet",
    "none",
    "none",
  ],
  [
    "queryExecutionStats",
    "runtime_context_query_execution_stats",
    "GET",
    "/v1/context/collections/by-name/{collection_name}/query-execution-stats",
    "readOnlyGet",
    "none",
    "none",
  ],
  ["rankFusion", "runtime_context_rank_fusion", "POST", "/v1/context/hybrid/rank-fusion", "never", "none", "required"],
  [
    "rawVectorSearch",
    "runtime_context_raw_vector_search",
    "POST",
    "/v1/context/search/raw",
    "never",
    "none",
    "required",
  ],
  ["recallCheck", "runtime_context_recall_check", "POST", "/v1/context/recall-check", "never", "none", "required"],
  ["recommend", "runtime_context_recommend", "POST", "/v1/context/recommend", "never", "none", "required"],
  [
    "reconcilePoints",
    "runtime_context_reconcile_points",
    "POST",
    "/v1/context/collections/{collection_id}/points/reconcile",
    "idempotentMutation",
    "none",
    "required",
  ],
  [
    "refreshOnboarding",
    "runtime_context_refresh_onboarding",
    "POST",
    "/v1/context/onboarding/refresh",
    "readOnlyPost",
    "none",
    "required",
  ],
  [
    "registerFilterColumn",
    "runtime_context_add_filter_column",
    "POST",
    "/v1/context/collections/{collection_id}/filters/columns",
    "idempotentMutation",
    "none",
    "required",
  ],
  [
    "registerJsonbPath",
    "runtime_context_add_filter_jsonb_path",
    "POST",
    "/v1/context/collections/{collection_id}/filters/jsonb-paths",
    "idempotentMutation",
    "none",
    "required",
  ],
  [
    "registerModelVersion",
    "runtime_context_register_model_version",
    "POST",
    "/v1/context/collections/by-name/{collection_name}/model-versions",
    "never",
    "none",
    "required",
  ],
  [
    "registerVector",
    "runtime_context_add_vector",
    "POST",
    "/v1/context/collections/{collection_id}/vectors",
    "idempotentMutation",
    "none",
    "required",
  ],
  [
    "reindexCollection",
    "runtime_context_reindex_collection",
    "POST",
    "/v1/context/collections/{collection_id}/reindex",
    "idempotentMutation",
    "none",
    "required",
  ],
  [
    "retryOperation",
    "runtime_context_retry_operation",
    "POST",
    "/v1/context/operations/{operation_id}/retry",
    "idempotentMutation",
    "none",
    "required",
  ],
  [
    "scroll",
    "runtime_context_scroll_points",
    "GET",
    "/v1/context/collections/{collection_id}/points",
    "readOnlyGet",
    "cursor",
    "none",
  ],
  [
    "scrollPoints",
    "runtime_context_scroll_points",
    "GET",
    "/v1/context/collections/{collection_id}/points",
    "readOnlyGet",
    "cursor",
    "none",
  ],
  ["search", "runtime_context_search", "POST", "/v1/context/search", "never", "none", "required"],
  [
    "setDefaultCollection",
    "runtime_context_update_collection",
    "PATCH",
    "/v1/context/collections/{collection_id}",
    "idempotentMutation",
    "none",
    "required",
  ],
  ["setPayload", "runtime_context_set_payload", "PUT", "/v1/context/points/payload", "never", "none", "required"],
  [
    "telemetry",
    "runtime_context_telemetry",
    "GET",
    "/v1/context/collections/by-name/{collection_name}/telemetry",
    "readOnlyGet",
    "none",
    "none",
  ],
  ["textHybrid", "runtime_context_text_hybrid", "POST", "/v1/context/hybrid/text", "never", "none", "required"],
  [
    "updateCollection",
    "runtime_context_update_collection",
    "PATCH",
    "/v1/context/collections/{collection_id}",
    "idempotentMutation",
    "none",
    "required",
  ],
  [
    "updateEmbeddingMigration",
    "runtime_context_update_embedding_migration",
    "PATCH",
    "/v1/context/collections/by-name/{collection_name}/embedding-migrations/{migration_id}",
    "never",
    "none",
    "required",
  ],
  [
    "upsertPoints",
    "runtime_context_upsert_points",
    "POST",
    "/v1/context/collections/{collection_id}/points/upsert",
    "idempotentMutation",
    "none",
    "required",
  ],
  [
    "vacuumAdvice",
    "runtime_context_vacuum_advice",
    "GET",
    "/v1/context/collections/by-name/{collection_name}/indexes/{index_name}/vacuum-advice",
    "readOnlyGet",
    "none",
    "none",
  ],
  [
    "vectorFirst",
    "runtime_context_vector_first",
    "POST",
    "/v1/context/hybrid/vector-first",
    "never",
    "none",
    "required",
  ],
  [
    "verifyCollection",
    "runtime_context_verify_collection",
    "POST",
    "/v1/context/collections/{collection_id}/verify",
    "readOnlyPost",
    "none",
    "none",
  ],
] as const satisfies ReadonlyArray<OperationTuple>

const locals = [
  "queryDiscover",
  "queryFormula",
  "queryFullText",
  "queryLateInteraction",
  "queryLookup",
  "queryNearest",
  "queryPrefetch",
  "queryRecommend",
  "queryRerank",
  "queryScoreThreshold",
  "querySparseNearest",
  "queryWeight",
] as const

export const contextBindings: ReadonlyArray<ContextBinding> = [
  ...operations.map(
    ([publicName, operationId, method, path, retryPolicy, pagination, requestBody]): ContextOperationBinding => ({
      kind: "operation",
      publicName,
      operationId,
      method,
      path,
      retryPolicy,
      pagination,
      requestBody,
    }),
  ),
  ...locals.map((publicName): ContextLocalBinding => ({ kind: "local", publicName })),
  {
    kind: "composite",
    publicName: "waitForOperation",
    operationId: "runtime_context_get_operation",
    method: "GET",
    path: "/v1/context/operations/{operation_id}",
    retryPolicy: "polling",
    pagination: "none",
    requestBody: "none",
  },
]
